<div class="container">
    <h2>КОРЗИНА</h2>
    <h2 class="card-deck">
        <a href="/main" > <h3 class="cart"> назад в каталог </h3> </a>
        <?php foreach ($products as $product): ?>
            <?php foreach ($cartProducts as $cartProduct):?>
                 <?php if ($cartProduct->getProductId() === $product->getId()): ?>
                    <form action="/cart" method="post">
                        <div class="card text-center">
                            <a href="#">
                                <div class="card-header">
                                    .
                                </div>
                                <img class="card-img-top" src=<?php echo $product->getImageLink() ?> alt="Card image">
                                <div class="card-body">
                                    <a href="#"><h3 class="card-title"><?php echo $product->getName() ?></h3></a>
                                    <label for="product_id"></label><input type="text" id="product_id" class="fadeIn second" name="product_id" placeholder="Product-id" hidden="" value="<?php echo $product->getId() ?>">
                                    <div class="quantity-price">
                                        <?php echo $cartProduct->getQuantity() . ' шт.'; ?>
                                    </div>
                                    <input type="submit" class="fadeIn fourth" value="Удалить товар">
                                    <div class="card-footer">
                                        <?php echo 'цена ' . $product->getPrice()*$cartProduct->getQuantity()." р." ?>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </form>
                 <?php endif; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
        <input type="submit" class="total-price" value=" <?php  echo 'Итого: ' . $sumTotalCart . ' р.'?>">
        <a href="/order" > <h3 class="cart">  оформите заказ  </h3> </a>
</div>
<style>
    body {
        font-style: normal;display:flex;
        justify-content: center;
        align-items: center;
        margin:50px auto;
    }

    a {
        text-decoration: none;
    }
    .card-deck {
        position: relative;
        /*border: solid orange;*/
        height: 50px;



    }
    .card-deck {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 50px;
    }

    .card {
        max-width: 23rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }


    .card-footer{
        position: absolute;
        color: black;
        font-weight: bold;
        font-size: 18px;
        background-color: red;
        border-radius:10px;
    }
    .total-price{
        font-size: 30px;
        color: blue;
        font-weight: bold;
    }
    .quantity-price {
        font-size: 25px;
        color: white;
        font-weight: bold;
        background-color: blue;
    }
    /*.order {*/
    /*    position: marker;*/
    /*    font-size: 20px;*/
    /*    color: white;*/
    /*    font-weight: bold;*/
    /*    background-color: green;*/
    /*    border-radius:10px;*/
    /*}*/
    .cart{
        font-size: 25px;
        position: marker;
        color: blue;
        font-weight: bold;
        /*background-color: blue;*/
        border-radius:30px;
    }
</style>