<div class="container">
    <h2>КАТАЛОГ</h2>
    <h2 class="card-deck">
        <a href="/login" > <h3 class="cart"> Login </h3> </a>
        <?php foreach ($products as $product): ?>
            <form action="/main" method="post" class="add_product">
                <div class="card text-center">
                    <a href="#">
                        <div class="card-header">
                            .
                        </div>
                        <img class="card-img-top" src=<?php echo $product->getImageLink() ?> alt="Card image">
                        <div class="card-body">
                            <a href="#"><h2 class="card-title"><?php echo $product->getName() ?></h2></a>
                            <a href="#"><h4 class="card-title"><?php echo $product->getDescription() ?></h4></a>
                            <label for="product_id"></label><input type="text" id="product_id" class="fadeIn second" name="product_id" placeholder="Product-id" hidden="" value="<?php echo $product->getId() ?>">
                            <label for="quantity"></label><input type="text" id="quantity" class="fadeIn third" name="quantity" placeholder="Quantity">
                            <input type="submit" class="fadeIn_fourth" value="Добавить в корзину">
                            <div class="card-footer">
                                <?php echo $product->getPrice() ." р." ?>
                            </div>
                        </div>
                    </a>
                </div>
            </form>
        <?php endforeach; ?>
<!--        <script-->
<!--                src="https://code.jquery.com/jquery-3.7.0.min.js"-->
<!--                integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="-->
<!--                crossorigin="anonymous">-->
<!--        </script>-->
<!--        <script type="text/javascript">-->
<!--            document.querySelectorAll('.add_product').forEach(function(form) {-->
<!--                form.addEventListener('submit', function(event) {-->
<!--                    event.preventDefault(); // Предотвращаем отправку формы-->
<!---->
<!--                    var formData = new FormData(form); // Создаем объект FormData и заполняем его значениями полей формы-->
<!---->
<!--                    fetch('/main', {-->
<!--                        method: 'POST',-->
<!--                        body: formData-->
<!--                    })-->
<!--                        .then(function(response) {-->
<!--                            console.log(response);-->
<!--                            return response.json();-->
<!--                        })-->
<!--                        .then(function(data) {-->
<!--                            console.log('успешно');-->
<!--                            // Обработка успешного ответа от сервера-->
<!--                        })-->
<!--                        .catch(function(error) {-->
<!--                            console.log('ошибка');-->
<!--                            // Обработка ошибок-->
<!--                        });-->
<!--                });-->
<!--            });-->
<!--        </script>-->
        <a href="/cart" > <h3 class="cart">  Корзина  </h3> </a>
    </div>
    <style>
        body {
            font-style: normal;display:flex;
            justify-content: center;
            align-items: center;
            margin:50px auto;
        }

        a {
            text-decoration: none;
        }
        .card-deck {
            position: relative;
            /*border: solid orange;*/
            height: 50px;



        }
        .card-deck {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        a:hover {
            text-decoration: none;
        }

        h3 {
            line-height: 2px;
        }

        .card {
            max-width: 23rem;
        }

        .card:hover {
            box-shadow: 1px 2px 10px lightgray;
            transition: 0.2s;
        }

        .card-header {
            font-size: 13px;
            color: greenyellow;
            font-weight: bold;
            background-color: blue;
        }

        .card-footer{
            position: absolute;
            color: black;
            font-weight: bold;
            font-size: 18px;
            background-color: red;
            border-radius:10px;
        }
        .cart{
            font-size: 25px;
            position: marker;
            color: blue;
            font-weight: bold;
            /*background-color: blue;*/
            border-radius:30px;
        }
    </style>